### ISSUE TITLE
Optimization: delay computing len of numeric_range until needed

### ISSUE THREAD

**Issue by eltoder** [more-itertools/more-itertools#673]
Instead of always computing `_len` in `__init__`, we can delay the computation until it is used. For simple iteration over the range, we can avoid computing it entirely. For other uses it will add negligible overhead.

**Comment by bbayles** [comment]
Is this an expensive calculation at all? I'm not sure there's much benefit to be had here - am I wrong?

**Comment by eltoder** [comment]
In my testing with dates, it accounts for half of the time to construct numeric_range and 20% of the time to iterate over the range with 9 dates.

Without the change:
```python
from more_itertools import numeric_range
from datetime import date, timedelta
d1 = date(2000, 1, 1)
d2 = date(2000, 1, 10)
%timeit numeric_range(d1, d2)
1.18 µs ± 7.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
r = numeric_range(d1, d2)
%timeit list(r)
2.86 µs ± 81.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

With the change
```python
%timeit numeric_range(d1, d2)
606 ns ± 5.27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
%timeit list(r)
2.87 µs ± 16.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

I think it's a nice improvement, given that it's so simple. The code can be even simpler if you are OK with adding a dependency on `cached-property` for python 3.7.

**Comment by bbayles** [comment]
If we're talking microseconds on a fairly complex data type like datetime, I think I'm okay to leave it be.

**Comment by eltoder** [comment]
We are spending 20-50% of time doing something unnecessary and easily avoidable in very realistic scenarios. It can become seconds or minutes if you put it in a loop.

**Comment by bbayles** [comment]
Hmm, how long does it take to import `functools`?

**Comment by eltoder** [comment]
The import is only done once at top level. Also `functools` is already imported by this module.

I updated my PR to include a very simple implementation of `cached_property` as a fallback. Now the code in `numeric_range` is very simple and clean without any staging checks.

**Comment by bbayles** [comment]
You're right that `functools` is already imported, thanks.

I'm still not inclined to bring in an implementation of `cached_property` to solve what I don't think is a common problem.

However, Python 3.7 goes end of life in four months. If you'll remove the manual implementation of `cache_property` from your PR and hold it until then, I'll merge it.

**Comment by elliotwutingfeng** [comment]
Python 3.7 is EOLed!
